services:
  - type: web
    name: panelpro-api
    env: python            # Python runtime
    plan: free             # or 'starter' / 'standard' if you change later
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true

  - type: web
    name: panelpro-frontend
    env: static            # <--- this makes it a static site
    rootDir: frontend
    buildCommand: ""       # no build step, just serve /frontend
    staticPublishPath: .
    autoDeploy: true
    plan: free